# Generated by Django 5.0.7 on 2024-08-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_labology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='test',
            new_name='tests',
        ),
    ]
