# Generated by Django 5.0.7 on 2024-08-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_labology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='test',
        ),
        migrations.AddField(
            model_name='patient',
            name='tests',
            field=models.ManyToManyField(related_name='patients', to='app_labology.test'),
        ),
    ]
