# Generated by Django 5.0.7 on 2024-08-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_labology', '0003_remove_patient_tests_test_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='patients',
        ),
        migrations.CreateModel(
            name='PatientTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_labology.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_labology.test')),
            ],
        ),
    ]
